# Generated by Django 2.1.4 on 2018-12-26 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Licorne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='Date de création')),
            ],
        ),
        migrations.AddField(
            model_name='etape',
            name='licorne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licornes.Licorne'),
        ),
    ]
