# Generated by Django 2.1.4 on 2019-01-05 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licornes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etape',
            name='auteur',
            field=models.ForeignKey(help_text="<br />Ce champ n'existe que pendant le temps de développement. Par la suite, il sera rempli automatiquement.", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='etape',
            name='localisation',
            field=models.CharField(default='Pau, France', help_text='<br />Saisissez une ville ou un pays, le champ se complètera automatiquement.', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etape',
            name='media',
            field=models.TextField(blank=True, help_text="<br />Ecrivez ici le code embed d'une vidéo.", null=True),
        ),
    ]
