# Generated by Django 2.1.4 on 2018-12-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licornes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etape',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etape',
            name='localisation',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='licorne',
            name='identifiant',
            field=models.CharField(default=112, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licorne',
            name='photo',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etape',
            name='etape_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='licorne',
            name='creation_date',
            field=models.DateField(verbose_name='Date de création'),
        ),
    ]
