# Generated by Django 2.1.4 on 2019-01-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licornes', '0001_squashed_0019_auto_20190103_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etape',
            name='current',
        ),
    ]
