# Generated by Django 2.1.4 on 2018-12-30 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licornes', '0003_auto_20181230_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etape',
            name='etape_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
