# Generated by Django 2.1.4 on 2018-12-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licornes', '0004_auto_20181230_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etape',
            name='localisation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='etape',
            name='media',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
