# Generated by Django 2.1.4 on 2018-12-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licornes', '0005_auto_20181230_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etape',
            name='localisation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='licorne',
            name='nom',
            field=models.CharField(max_length=50),
        ),
    ]
