# Generated by Django 2.1.4 on 2018-12-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licornes', '0006_auto_20181230_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licorne',
            name='photo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
