# Generated by Django 2.1.4 on 2018-12-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licornes', '0007_auto_20181230_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etape',
            name='localisation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='etape',
            name='media',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
