# Generated by Django 2.1.4 on 2019-01-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licornes', '0008_auto_20181230_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licorne',
            name='identifiant',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
