# Generated by Django 2.1.4 on 2019-01-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licornes', '0010_auto_20190101_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etape',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='etape',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
