# Generated by Django 2.1.4 on 2019-01-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licornes', '0011_auto_20190101_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etape',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etape',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
