# Generated by Django 2.1.4 on 2019-01-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licornes', '0013_auto_20190102_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='licorne',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
