# Generated by Django 2.1.4 on 2019-01-03 14:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licornes', '0015_remove_licorne_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etape',
            name='auteur',
            field=models.ForeignKey(help_text="Ce champ n'existe que pendant le temps de développement. Par la suite, il sera rempli automatiquement.", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='etape',
            name='etape_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='etape',
            name='localisation',
            field=models.CharField(blank=True, help_text='<br />Saisissez une ville ou un pays, le champ se complètera automatiquement.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='etape',
            name='media',
            field=models.TextField(blank=True, help_text="Ecrivez ici le code embed d'une vidéo.", null=True),
        ),
        migrations.AlterField(
            model_name='licorne',
            name='createur',
            field=models.ForeignKey(help_text="Ce champ n'existe que pendant le temps de développement. Par la suite, il sera rempli automatiquement.", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='licorne',
            name='identifiant',
            field=models.CharField(help_text="Saisissez l'identifiant qui figure sur votre licorne.", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='licorne',
            name='image',
            field=models.ImageField(blank=True, help_text='Mettez une photo de votre licorne, ou un avatar.', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='licorne',
            name='nom',
            field=models.CharField(help_text='Choisissez un nom pour votre licorne.', max_length=50),
        ),
    ]
