# Generated by Django 2.1.4 on 2019-01-03 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licornes', '0017_auto_20190103_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licorne',
            name='creation_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date de création'),
        ),
    ]
