# Generated by Django 2.1.4 on 2019-01-03 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('licornes', '0018_auto_20190103_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etape',
            name='etape_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
